In [1]:
import wandb

# Initialize the API
api = wandb.Api()

# Replace "my-user-name" and "my-project-name" with your username and project name
runs = api.runs("mattdevries/TransTest")


test_accuracies = {}

for run in runs:
    if 'test_acc_epoch' in run.summary:
        test_accuracies[run.name] = run.summary['test_acc_epoch']

print(test_accuracies)


{'Palbociclib_fold_9': 0.9777777791023254, 'PF228_fold_9': 0.9333333373069764, 'Nocodazole_fold_9': 1, 'MK1775_fold_9': 0.7333333492279053, 'H1152_fold_9': 0.9777777791023254, 'DMSO_fold_9': 0.8666666746139526, 'CK666_fold_9': 0.9111111164093018, 'Blebbistatin_fold_9': 1, 'Binimetinib_fold_9': 0.9111111164093018, 'Palbociclib_fold_8': 0.9333333373069764, 'PF228_fold_8': 0.8666666746139526, 'Nocodazole_fold_8': 1, 'MK1775_fold_8': 0.8222222328186035, 'H1152_fold_8': 0.9555555582046508, 'DMSO_fold_8': 0.800000011920929, 'CK666_fold_8': 0.8888888955116272, 'Blebbistatin_fold_8': 0.9777777791023254, 'Binimetinib_fold_8': 0.8888888955116272, 'Palbociclib_fold_7': 0.9333333373069764, 'PF228_fold_7': 0.9111111164093018, 'Nocodazole_fold_7': 1, 'MK1775_fold_7': 0.8666666746139526, 'H1152_fold_7': 1, 'DMSO_fold_7': 0.8666666746139526, 'CK666_fold_7': 0.9333333373069764, 'Blebbistatin_fold_7': 1, 'Binimetinib_fold_7': 0.8888888955116272, 'Palbociclib_fold_6': 0.9333333373069764, 'PF228_fold_6': 

In [2]:
import pandas as pd

df = pd.DataFrame(test_accuracies, index=[0])

In [3]:
df_correct = df.iloc[:,:-9]

In [4]:
df_correct = df_correct.T

In [5]:
df_correct['Drug'] = [i.split('_')[0] for i in df_correct.index]
df_correct['Fold'] = [i.split('_')[2] for i in df_correct.index]


In [6]:
df_correct['Fold']

Palbociclib_fold_9     9
PF228_fold_9           9
Nocodazole_fold_9      9
MK1775_fold_9          9
H1152_fold_9           9
                      ..
H1152_fold_1           1
DMSO_fold_1            1
CK666_fold_1           1
Blebbistatin_fold_1    1
Binimetinib_fold_1     1
Name: Fold, Length: 81, dtype: object

In [7]:
df_correct.groupby('Drug').mean()

0         Fold
Drug                               
Binimetinib   0.911111  109739369.0
Blebbistatin  0.980247  109739369.0
CK666         0.925926  109739369.0
DMSO          0.809877  109739369.0
H1152         0.953086  109739369.0
MK1775        0.834568  109739369.0
Nocodazole    0.997531  109739369.0
PF228         0.893827  109739369.0
Palbociclib   0.930864  109739369.0

In [8]:
df_correct.groupby('Drug').std()

0      Fold
Drug                            
Binimetinib   0.036851  2.738613
Blebbistatin  0.023424  2.738613
CK666         0.033333  2.738613
DMSO          0.068594  2.738613
H1152         0.043666  2.738613
MK1775        0.052247  2.738613
Nocodazole    0.007407  2.738613
PF228         0.036477  2.738613
Palbociclib   0.030316  2.738613

In [30]:
import torch

x = torch.randn(1)
x

tensor([-1.2141])

In [31]:
torch.sigmoid(x)

tensor([0.2290])

In [34]:
print(torch.sigmoid(x))

print(int(torch.sigmoid(x)))

tensor([0.2290])
0
